# Write your MySQL query statement below
SELECT 
ACTIVITY_DATE as day,
COUNT(DISTINCT USER_ID) AS active_users
FROM ACTIVITY 
WHERE DATE(ACTIVITY_DATE) BETWEEN '2019-06-28' AND '2019-07-27'
GROUP BY ACTIVITY_DATE 